CREATE
DATABASE receipt_data;

CREATE TABLE product(
    id    int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  varchar(50)   NOT NULL,
    price numeric(6, 2) NOT NULL
);

CREATE TABLE discount_card(
    id     int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number int NOT NULL
);

INSERT INTO product(name, price) VALUES ('Shampoo 500ml', 3.95);
INSERT INTO product(name, price) VALUES ('Deodorant 150ml', 2.99);
INSERT INTO product(name, price) VALUES ('Drinking water 1.5l', 0.99);
INSERT INTO product(name, price) VALUES ('Banana', 2.45);
INSERT INTO product(name, price) VALUES ('Cookie', 1.93);
INSERT INTO product(name, price) VALUES ('Dark chocolate', 4.05);
INSERT INTO product(name, price) VALUES ('Georgian red wine', 8.99);
INSERT INTO product(name, price) VALUES ('Beer 0.5l', 3.20);
INSERT INTO product(name, price) VALUES ('Toothpaste', 5.95);
INSERT INTO product(name, price) VALUES ('Book Java. Herbert Schildt', 69.0);

INSERT INTO discount_card(number) VALUES (1);
INSERT INTO discount_card(number) VALUES (11);
INSERT INTO discount_card(number) VALUES (111);
INSERT INTO discount_card(number) VALUES (1234);